[package]
name = "urdict"
version = "0.1.0"
authors = ["Ning Sun <sunng@about.me>"]

[dependencies]
clap = "*"
hyper = "*"
kuchiki =  { git = "https://github.com/SimonSapin/kuchiki" }
ansi_term = "*"
string_cache = "*"
rand = "*"
